#!/usr/bin/env python3
"""
Phase 0B.2 — Video Curation Register & Homepage Reel Source Plan
Reads 02A asset master → generates 02T_VIDEO_CURATION_REGISTER.csv + 02U_HOMEPAGE_REEL_SOURCE_PLAN.md
"""

import csv
import os
import re
from collections import defaultdict

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
DOCS = os.path.join(REPO_ROOT, "docs")
PHASE0B = os.path.join(DOCS, "phase-0b")
OUTPUT = os.path.join(DOCS, "phase-0b")

ASSET_MASTER = os.path.join(PHASE0B, "02A_LOCAL_ASSET_MASTER.csv")


def size_tier(size_bytes):
    if size_bytes >= 15_000_000:
        return "LARGE"
    elif size_bytes >= 5_000_000:
        return "MEDIUM"
    elif size_bytes >= 2_000_000:
        return "SMALL"
    return "VERY_SMALL"


def infer_content_hint(filename_stem):
    stem = filename_stem.lower()
    if re.match(r'^\d+[a-z]?$', stem):
        return "UNIDENTIFIED"
    return "DESCRIPTIVE"


def flag_potential_duplicate(videos):
    size_groups = defaultdict(list)
    for v in videos:
        size = int(v.get("size_bytes", 0))
        size_groups[size].append(v["asset_id"])
    dup_map = {}
    for size, aids in size_groups.items():
        if len(aids) > 1 and size > 1_000_000:
            for aid in aids:
                dup_map[aid] = "|".join(aids)
    return dup_map


def main():
    print("Loading asset master...")
    with open(ASSET_MASTER) as f:
        assets = list(csv.DictReader(f))

    videos = [a for a in assets if a.get("media_class") == "VIDEO"]
    print(f"  {len(videos)} videos found")

    dup_map = flag_potential_duplicate(videos)

    print("\nClassifying videos...")
    results = []
    for v in videos:
        aid = v["asset_id"]
        size = int(v.get("size_bytes", 0))
        stem = v.get("filename_stem", "")
        content_hint = infer_content_hint(stem)

        row = {
            "asset_id": aid,
            "filename": v.get("filename", ""),
            "size_bytes": size,
            "size_mb": round(size / 1024 / 1024, 2),
            "size_tier": size_tier(size),
            "content_hint": content_hint,
            "potential_duplicate_group": dup_map.get(aid, ""),
            "source_folder": v.get("parent_folder", ""),
            "visual_review_status": "NOT_REVIEWED",
            "identified_content": "",
            "project_assignment": "",
            "reel_candidate": "",
            "reel_priority": "",
            "notes": "",
        }
        results.append(row)

    results.sort(key=lambda x: x["size_bytes"], reverse=True)

    fieldnames = [
        "asset_id", "filename", "size_bytes", "size_mb", "size_tier",
        "content_hint", "potential_duplicate_group", "source_folder",
        "visual_review_status", "identified_content", "project_assignment",
        "reel_candidate", "reel_priority", "notes",
    ]

    outpath = os.path.join(OUTPUT, "02T_VIDEO_CURATION_REGISTER.csv")
    with open(outpath, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(results)
    print(f"Written: {outpath}")

    tier_counts = defaultdict(int)
    for r in results:
        tier_counts[r["size_tier"]] += 1
    print(f"\nSize distribution:")
    for t in ["LARGE", "MEDIUM", "SMALL", "VERY_SMALL"]:
        print(f"  {t}: {tier_counts.get(t, 0)}")

    dup_count = len(set(dup_map.values()))
    print(f"\nPotential duplicate groups: {dup_count}")

    generate_reel_plan(results, dup_map)


def generate_reel_plan(videos, dup_map):
    print("\nGenerating homepage reel source plan...")

    large = [v for v in videos if v["size_tier"] == "LARGE"]
    medium = [v for v in videos if v["size_tier"] == "MEDIUM"]

    lines = []
    lines.append("# Homepage Reel Source Plan")
    lines.append("")
    lines.append("> Phase 0B.2 — Auto-generated by generate_video_curation.py")
    lines.append("> Source: 02A_LOCAL_ASSET_MASTER.csv (VIDEO assets only)")
    lines.append("")
    lines.append("## Overview")
    lines.append("")
    lines.append(f"- **Total video assets**: {len(videos)}")
    lines.append(f"- **Large (>15MB)**: {len(large)}")
    lines.append(f"- **Medium (5-15MB)**: {len(medium)}")
    lines.append(f"- **Potential duplicate groups**: {len(set(dup_map.values()))}")
    lines.append(f"- **All videos**: single VIDEO/ folder, generic numeric filenames")
    lines.append(f"- **Resolution metadata**: NOT AVAILABLE (ffprobe not run)")
    lines.append("")
    lines.append("## Status: REQUIRES VISUAL REVIEW")
    lines.append("")
    lines.append("All 45 videos need visual review before reel selection. Without ffprobe or visual")
    lines.append("inspection, content cannot be determined from filenames alone.")
    lines.append("")
    lines.append("## Priority Review List")
    lines.append("")
    lines.append("These are the largest files — most likely to contain usable footage.")
    lines.append("")
    lines.append("| Asset | File | Size | Notes |")
    lines.append("|-------|------|------|-------|")

    for v in videos[:15]:
        dup_note = ""
        if v["potential_duplicate_group"]:
            dup_note = f"⚠ Possible duplicate of {v['potential_duplicate_group']}"
        lines.append(f"| {v['asset_id']} | {v['filename']} | {v['size_mb']}MB | {dup_note} |")

    lines.append("")
    lines.append("## Reel Selection Criteria")
    lines.append("")
    lines.append("For homepage hero reel, prioritize:")
    lines.append("")
    lines.append("1. **Visual impact** — Strong composition, motion, lighting")
    lines.append("2. **Process content** — Manufacturing, prototyping, assembly (shows capability)")
    lines.append("3. **Final product shots** — Beauty shots, lifestyle, in-use")
    lines.append("4. **Technical content** — Engineering, testing, validation")
    lines.append("5. **Resolution** — Minimum 1080p preferred, 4K ideal")
    lines.append("")
    lines.append("## Next Steps")
    lines.append("")
    lines.append("1. Run `ffprobe` on each video to get resolution, duration, codec, framerate")
    lines.append("2. Visual review: watch each clip, classify content type")
    lines.append("3. Assign to projects where identifiable")
    lines.append("4. Select 5-10 clips for homepage reel")
    lines.append("5. Identify any clips needing color correction or stabilization")
    lines.append("")
    lines.append("## ffprobe Batch Command")
    lines.append("")
    lines.append("```bash")
    lines.append('for f in "Images & Videos/VIDEO/"*.mp4; do')
    lines.append('  echo "=== $(basename "$f") ==="')
    lines.append('  ffprobe -v quiet -print_format json -show_streams "$f" | \\')
    lines.append('    python3 -c "import sys,json; d=json.load(sys.stdin);')
    lines.append('s=[x for x in d[\"streams\"] if x[\"codec_type\"]==\"video\"];')
    lines.append('print(f\"  {s[0][\"width\"]}x{s[0][\"height\"]} {s[0].get(\"duration\",\"?\")}s {s[0].get(\"codec_name\",\"?\")}\") if s else print(\"  no video stream\")"')
    lines.append("done")
    lines.append("```")

    outpath = os.path.join(OUTPUT, "02U_HOMEPAGE_REEL_SOURCE_PLAN.md")
    with open(outpath, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Written: {outpath}")


if __name__ == "__main__":
    main()
